# Generated by Django 4.1.7 on 2023-04-26 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='LogType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=500)),
                ('maxTimeSla', models.TimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='QueueProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField(null=True)),
                ('endDate', models.DateField(null=True)),
                ('state', models.CharField(max_length=256)),
                ('idConfiguration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='main.processconfiguration')),
                ('idLabels', models.ManyToManyField(blank=True, related_name='labels', to='main.label')),
            ],
        ),
        migrations.CreateModel(
            name='QueueTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField()),
                ('state', models.CharField(max_length=256)),
                ('idProcess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process', to='main.queueprocess')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameSkill', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=500)),
                ('idPermissions', models.ManyToManyField(related_name='teamPermissions', to='auth.group')),
                ('idSkils', models.ManyToManyField(related_name='skills', to='main.skill')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recoveryCode', models.CharField(blank=True, max_length=10)),
                ('goal', models.IntegerField(default=100)),
                ('lastCodeSentTime', models.DateTimeField(blank=True, null=True)),
                ('idGroupUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupUser', to='auth.group')),
                ('idSkills', models.ManyToManyField(related_name='skillUser', to='main.skill')),
                ('idTeam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipaMembros', to='main.team')),
                ('idUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('access_admin_page', 'Can access the admin page'), ('access_analytic_page', 'Can access the analytic page'), ('access_operational_page', 'Can access the operational page')],
            },
        ),
        migrations.AddField(
            model_name='team',
            name='idTeamLider',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teamLider', to='main.userprofile'),
        ),
        migrations.CreateModel(
            name='TaskConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=500)),
                ('maxTimeSla', models.TimeField(null=True)),
                ('idProcessConfiguration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processConfiguration', to='main.processconfiguration')),
                ('idtaskType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskType', to='main.tasktype')),
            ],
        ),
        migrations.CreateModel(
            name='SLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField(null=True)),
                ('endDate', models.DateField(null=True)),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=600)),
                ('idTask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SlaTask', to='main.queuetask')),
            ],
        ),
        migrations.CreateModel(
            name='Reporting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=2000)),
                ('tasks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportingTasks', to='main.queuetask')),
            ],
        ),
        migrations.AddField(
            model_name='queuetask',
            name='idTaskConfiguration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskConfiguration', to='main.taskconfiguration'),
        ),
        migrations.AddField(
            model_name='queueprocess',
            name='idUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userProfile', to='main.userprofile'),
        ),
        migrations.AddField(
            model_name='processconfiguration',
            name='idProcessType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processType', to='main.processtype'),
        ),
        migrations.AddField(
            model_name='processconfiguration',
            name='idSkills',
            field=models.ManyToManyField(related_name='ProcessConfigurationSkill', to='main.skill'),
        ),
        migrations.AddField(
            model_name='processconfiguration',
            name='idTeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProcessConfigurationTeam', to='main.team'),
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ficheiro', models.FileField(max_length=254, upload_to=main.models.log_path)),
                ('date', models.DateField(null=True)),
                ('logType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logType', to='main.logtype')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='main.queuetask')),
            ],
        ),
    ]
