# Generated by Django 4.2 on 2023-04-24 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='LogType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField(null=True)),
                ('endDate', models.DateField(null=True)),
                ('state', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=500)),
                ('maxTimeSla', models.TimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='SLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField(null=True)),
                ('endDate', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField()),
                ('state', models.CharField(max_length=256)),
                ('startDate', models.DateField(null=True)),
                ('endDate', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recoveryCode', models.CharField(blank=True, max_length=10)),
                ('goal', models.IntegerField(default=100)),
                ('lastCodeSentTime', models.DateTimeField(blank=True, null=True)),
                ('groupUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupUser', to='auth.group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('access_admin_page', 'Can access the admin page'), ('access_analytic_page', 'Can access the analytic page'), ('access_operational_page', 'Can access the operational page')],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=500)),
                ('members', models.ManyToManyField(related_name='members', to='main.userprofile')),
                ('permissions', models.ManyToManyField(related_name='teamPermissions', to='auth.group')),
                ('tasks', models.ManyToManyField(related_name='tasks', to='main.task')),
                ('teamLider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teamLider', to='main.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TaskConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=500)),
                ('maxTimeSla', models.TimeField(null=True)),
                ('processConfiguration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processConfiguration', to='main.processconfiguration')),
                ('sla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TaskConfigurationSla', to='main.sla')),
                ('taskType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskType', to='main.tasktype')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='configuration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskConfiguration', to='main.taskconfiguration'),
        ),
        migrations.AddField(
            model_name='task',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process', to='main.process'),
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taskUser', to='main.userprofile'),
        ),
        migrations.CreateModel(
            name='Reporting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=2000)),
                ('tasks', models.ManyToManyField(related_name='reportingTasks', to='main.task')),
            ],
        ),
        migrations.AddField(
            model_name='processconfiguration',
            name='processType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processType', to='main.processtype'),
        ),
        migrations.AddField(
            model_name='processconfiguration',
            name='sla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProcessConfigurationSla', to='main.sla'),
        ),
        migrations.AddField(
            model_name='process',
            name='configuration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='main.processconfiguration'),
        ),
        migrations.AddField(
            model_name='process',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='labels', to='main.label'),
        ),
        migrations.AddField(
            model_name='process',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processUser', to='main.userprofile'),
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ficheiro', models.FileField(max_length=254, upload_to=main.models.log_path)),
                ('logType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logType', to='main.logtype')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='main.task')),
            ],
        ),
    ]
