# Generated by Django 4.1.7 on 2023-03-31 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='LogsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicialDate', models.DateField(null=True)),
                ('finalDate', models.DateField(null=True)),
                ('state', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='SLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicialDate', models.DateField(null=True)),
                ('finalDate', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.IntegerField(default=0)),
                ('idPerfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth.User.groups+', to='auth.group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='User.user+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamName', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=500)),
                ('permitionTeam', models.ManyToManyField(related_name='permitionTeam', to='auth.group')),
                ('team', models.ManyToManyField(related_name='team', to='main.user')),
            ],
        ),
        migrations.CreateModel(
            name='Task_Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=500)),
                ('maxTimeSLA', models.TimeField(null=True)),
                ('idProcessConfiguration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.process')),
                ('idSLA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sla')),
                ('taskType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tasktype')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField()),
                ('state', models.CharField(max_length=256)),
                ('inicialDate', models.DateField(null=True)),
                ('finalDate', models.DateField(null=True)),
                ('idProcess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.process')),
                ('idTaskConfiguration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idTaskConfiguration', to='main.process')),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
                ('team', models.ManyToManyField(related_name='tasks', to='main.team')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=500)),
                ('maxTimeSLA', models.TimeField(null=True)),
                ('idProcessType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.processtype')),
                ('idSLA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sla')),
            ],
        ),
        migrations.AddField(
            model_name='process',
            name='idProcessConfiguration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.processconfiguration'),
        ),
        migrations.AddField(
            model_name='process',
            name='idUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user'),
        ),
        migrations.AddField(
            model_name='process',
            name='label',
            field=models.ManyToManyField(blank=True, related_name='label', to='main.label'),
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ficheiro', models.FileField(max_length=254, upload_to='Logs/% Y/% m/% d/15:27_$<django.db.models.fields.related.ForeignKey>.txt')),
                ('idLogType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.logstype')),
                ('idTask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.task')),
            ],
        ),
    ]
