# Generated by Django 4.1.7 on 2023-04-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuetask',
            name='inputData',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
