# Generated by Django 4.1.7 on 2023-05-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdata',
            name='errorMessage',
            field=models.CharField(default='No error or warning', max_length=10000),
        ),
        migrations.AlterField(
            model_name='taskconfiguration',
            name='responsibility',
            field=models.CharField(max_length=50),
        ),
    ]
