# Generated by Django 4.1.7 on 2023-05-21 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='process',
            new_name='idProcess',
        ),
        migrations.RenameField(
            model_name='processconfiguration',
            old_name='maxTimeSla',
            new_name='maxTimeKPI',
        ),
        migrations.RenameField(
            model_name='reporting',
            old_name='user',
            new_name='idUser',
        ),
        migrations.RenameField(
            model_name='taskconfiguration',
            old_name='maxTimeSla',
            new_name='maxTimeKPI',
        ),
    ]
