# Generated by Django 4.1.7 on 2023-03-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='ficheiro',
            field=models.FileField(max_length=254, upload_to='Logs/% Y/% m/% d/09:23_$<django.db.models.fields.related.ForeignKey>.txt'),
        ),
    ]
