# Generated by Django 3.2.18 on 2023-04-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuetask',
            name='outputData',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
