# Generated by Django 4.1.7 on 2023-04-30 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_queuetask_outputdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='idTask',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='KPITask', to='main.queuetask'),
        ),
    ]
