# Generated by Django 4.1.7 on 2023-03-31 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_logs_ficheiro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('access_admin_page', 'Can access the admin page'), ('access_analytic_page', 'Can access the analytic page'), ('access_operational_page', 'Can access the operational page')]},
        ),
        migrations.AlterField(
            model_name='logs',
            name='ficheiro',
            field=models.FileField(max_length=254, upload_to='Logs/% Y/% m/% d/23:26_$<django.db.models.fields.related.ForeignKey>.txt'),
        ),
    ]
