# Generated by Django 4.1.7 on 2023-05-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_process_log_idprocess_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuetask',
            name='startWorkingDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
