# Generated by Django 4.1.7 on 2023-04-28 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_queuetask_inputdata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SLA',
            new_name='KPI',
        ),
    ]
