# Generated by Django 4.1.7 on 2023-04-28 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_sla_kpi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queueprocess',
            name='idUser',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='userProfile', to='main.userprofile'),
        ),
    ]
