# Generated by Django 4.1.7 on 2023-04-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_user_options_alter_logs_ficheiro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='ficheiro',
            field=models.FileField(max_length=254, upload_to='Logs/% Y/% m/% d/13:46_$<django.db.models.fields.related.ForeignKey>.txt'),
        ),
    ]
