# Generated by Django 4.1.7 on 2023-05-10 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_kpi_idtask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporting',
            name='tasks',
        ),
        migrations.AddField(
            model_name='reporting',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportingTasks', to='main.userprofile'),
        ),
    ]
