# Generated by Django 4.1.4 on 2023-04-24 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_task_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='codigoRecuperacao',
            new_name='recoveryCode',
        ),
    ]
