# Generated by Django 4.1.7 on 2023-05-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_queuetask_startworkingdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueprocess',
            name='registerDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
