# Generated by Django 4.1.7 on 2023-05-10 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_reporting_tasks_reporting_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporting',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportingUser', to='main.userprofile'),
        ),
    ]
