# Generated by Django 4.1.4 on 2023-04-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_codigorecuperacao_userprofile_recoverycode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='recoveryCode',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
