# Generated by Django 4.1.7 on 2023-04-01 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_logs_ficheiro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='ficheiro',
            field=models.FileField(max_length=254, upload_to='Logs/% Y/% m/% d/18:45_$<django.db.models.fields.related.ForeignKey>.txt'),
        ),
        migrations.AlterField(
            model_name='task',
            name='idTaskConfiguration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idTaskConfiguration', to='main.task_configuration'),
        ),
    ]
