# Generated by Django 4.1.7 on 2023-05-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_queueprocess_registerdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporting',
            name='ficheiro',
            field=models.FileField(blank=True, max_length=254, upload_to='static/files/ReportingErros/'),
        ),
    ]
