# Generated by Django 4.1.7 on 2023-04-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_logs_ficheiro_alter_task_idtaskconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='ficheiro',
            field=models.FileField(max_length=254, upload_to='Logs/% Y/% m/% d/18:47_$<django.db.models.fields.related.ForeignKey>.txt'),
        ),
    ]
