# Generated by Django 4.1.7 on 2023-05-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_reporting_ficheiro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporting',
            name='ficheiro',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to='static/files/ReportingErros/'),
        ),
    ]
