# Generated by Django 4.1.7 on 2023-03-31 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_logs_ficheiro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='ficheiro',
            field=models.FileField(max_length=254, upload_to='Logs/% Y/% m/% d/15:16_$<django.db.models.fields.related.ForeignKey>.txt'),
        ),
        migrations.AlterField(
            model_name='process',
            name='label',
            field=models.ManyToManyField(blank=True, related_name='label', to='main.label'),
        ),
    ]
