# Generated by Django 4.1.7 on 2023-03-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_logs_ficheiro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='ficheiro',
            field=models.FileField(max_length=254, upload_to='Logs/% Y/% m/% d/17:04_$<django.db.models.fields.related.ForeignKey>.txt'),
        ),
    ]
