# Generated by Django 3.2.19 on 2023-06-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_reporting_ficheiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='processconfiguration',
            name='latestOperation',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
