# Generated by Django 4.1.7 on 2023-03-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_logs_ficheiro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Static',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('alex_meow', 'can change name of product'),)},
        ),
        migrations.AddField(
            model_name='process',
            name='label',
            field=models.ManyToManyField(related_name='label', to='main.label'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='ficheiro',
            field=models.FileField(max_length=254, upload_to='Logs/% Y/% m/% d/17:42_$<django.db.models.fields.related.ForeignKey>.txt'),
        ),
    ]
