# Generated by Django 4.1.7 on 2023-03-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_delete_static_alter_user_options_process_label_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('alex_meow', 'meowmeowmeowmeow'),)},
        ),
        migrations.AlterField(
            model_name='logs',
            name='ficheiro',
            field=models.FileField(max_length=254, upload_to='Logs/% Y/% m/% d/17:44_$<django.db.models.fields.related.ForeignKey>.txt'),
        ),
    ]
