# Generated by Django 3.2.19 on 2023-06-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_processconfiguration_latestoperation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queueprocess',
            name='idLabels',
        ),
        migrations.AddField(
            model_name='processconfiguration',
            name='idLabels',
            field=models.ManyToManyField(blank=True, related_name='labels', to='main.Label'),
        ),
    ]
