# Generated by Django 4.1.7 on 2023-06-13 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20230603_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='idTeamLider',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='teamLider', to='main.userprofile'),
        ),
    ]
