# Generated by Django 4.1.7 on 2023-03-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_logs_ficheiro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('access_stats', 'Can access stats')]},
        ),
        migrations.AlterField(
            model_name='logs',
            name='ficheiro',
            field=models.FileField(max_length=254, upload_to='Logs/% Y/% m/% d/17:54_$<django.db.models.fields.related.ForeignKey>.txt'),
        ),
    ]
