# Generated by Django 4.1.7 on 2023-06-13 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_team_idteamlider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queueprocess',
            name='idUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='userProfile', to='main.userprofile'),
        ),
    ]
