# Generated by Django 4.1.7 on 2023-06-13 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0012_alter_queueprocess_iduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='idGroupUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='groupUser', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='idTeam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='equipaMembros', to='main.team'),
        ),
    ]
