# Generated by Django 4.1.7 on 2023-06-13 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_userprofile_idgroupuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='idTeam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipaMembros', to='main.team'),
        ),
    ]
