# Generated by Django 4.1.7 on 2023-03-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_user_options_alter_logs_ficheiro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('access_stats', 'Can access meow'), ('access_meow', 'Can access meowmeow'), ('admin_stats', 'Can access meow5')]},
        ),
        migrations.AlterField(
            model_name='logs',
            name='ficheiro',
            field=models.FileField(max_length=254, upload_to='Logs/% Y/% m/% d/17:56_$<django.db.models.fields.related.ForeignKey>.txt'),
        ),
    ]
