# Generated by Django 4.1.7 on 2023-06-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_userprofile_idteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueprocess',
            name='emailWasSeended',
            field=models.BooleanField(default=False),
        ),
    ]
