# Generated by Django 4.1.7 on 2023-06-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_queueprocess_emailwasseended'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='emailWasSeended',
            field=models.BooleanField(default=False),
        ),
    ]
