# Generated by Django 4.1.7 on 2023-06-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_team_emailwasseended'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='emailWasSeended',
        ),
        migrations.AddField(
            model_name='team',
            name='emailLastSeendDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
