# Generated by Django 4.1.7 on 2023-06-22 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_team_emailwasseended_team_emaillastseenddate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queueprocess',
            old_name='emailWasSeended',
            new_name='EmailWasSent',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='emailLastSeendDate',
            new_name='EmailWasSent',
        ),
    ]
